### ISSUE TITLE
Make the power client debug optional based on the verbose level via -v flag

### ISSUE THREAD

**Issue by mkumatag** [openshift/cluster-api-provider-powervs#10]
Currently, the power client is created, and debug flag is set as true by default, can see https://github.com/openshift/cluster-api-provider-powervs/blob/9eee608012a57a82fd7cc60507194572fdcc5201/pkg/client/powervs_client.go#L171, third param(debug param name in the function declaration).

Instead of this hardcoding, need to find a suitable verbose level and enable it via `-v` global flag.

**Comment by Karthik-K-N** [comment]
Submitted a PR for this issue: https://github.com/openshift/cluster-api-provider-powervs/pull/11

**Comment by mkumatag** [comment]
> Submitted a PR for this issue: #11

you can use `Fixes: #` tag in the PR to autoclose the associated issue when PR merges :) more [info](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

/close
