### ISSUE TITLE
Expected custom service endpoints and thier names or short names

### ISSUE THREAD

**Issue by Karthik-K-N** [openshift/cluster-api-provider-powervs#32]
Custom service endpoints provides the flexibility mention the various services and their respective url endpoints.

By supporting custom service endpoints , It makes easy to test the code against the staging area without need to modify anything.

(How the similar issue is resolved in aws : https://github.com/openshift/enhancements/blob/ce4d303db807622687159eb9d3248285a003fabb/enhancements/installer/aws-custom-region-and-endpoints.md)

Few of the service endpoints used in power vs capi are as below:

1. IAM [endpoint](https://github.com/openshift/cluster-api-provider-powervs/blob/3554fa46a4640ed894b3c46c5c465d7be82aaf53/vendor/github.com/IBM-Cloud/bluemix-go/authentication/iam.go#L51)
2. Resource controller [endpoint](https://github.com/openshift/cluster-api-provider-powervs/blob/3554fa46a4640ed894b3c46c5c465d7be82aaf53/vendor/github.com/IBM-Cloud/bluemix-go/api/resource/resourcev2/controllerv2/api_service.go#L53)
3. Power [endpoint](https://github.com/openshift/cluster-api-provider-powervs/blob/3554fa46a4640ed894b3c46c5c465d7be82aaf53/vendor/github.com/IBM-Cloud/power-go-client/ibmpisession/ibmpowersession.go#L88)

The goal here is to list all the expected or supported service endpoint and their name or short names to be used

Jira Task: https://issues.redhat.com/browse/MULTIARCH-1681

**Comment by mkumatag** [comment]
this is merged, hence can be closed. -Thanks.
